#pragma config(Motor,  port2,           steering,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           noisy,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void pre_auton() {
}

task autonomous() {
}

int vexRTT[6];  // Thresholded joystick
task usercontrol() {
    bool gateIsDown = false;
    while (true) {
        // Only run 50 times a second
        delay(20);
	    for (int i = 0; i < 6; i++)
	        vexRTT[i] = abs(vexRT[i]) > 10 ? vexRT[i] : 0;

        // drive
        motor[left]     = vexRTT[Ch3];
        motor[right]    = vexRTT[Ch3];
        motor[steering] = vexRTT[Ch1];

        if (vexRT[Btn8U])
            motor[noisy] = 127;
        else if (vexRT[Btn8R])
            motor[noisy] = 60;
        else if (vexRT[Btn8D])
            motor[noisy] = 30;
        else if (vexRT[Btn8L])
            motor[noisy] = 15;
        else
            motor[noisy] = 0;
    } // while (true)
} // Usercontrol
