#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           driveRight1,   tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           driveRight2,   tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           driveLeft2,    tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           driveLeft1,    tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "TrueSpeed.h"
#include "setDrive_2.1.3.c"
#include "mattsFunctions_1.1.3.c"

void pre_auton() {
    setDriveInit();
}

task autonomous() {

}

task usercontrol() {
    while (true) {
        // Only run 50 times a second
        delay(20);

        makeJoystickDeadzones();
        arcadeControl();
    } // while (true)
} // Usercontrol
